### ISSUE TITLE
Error while running the bot

### ISSUE THREAD

**Issue by AlejandroDieg0** [samirsalman/AmazonOffers-TelegramBot#1]
Hi, when start running the bot it says.
```

Error calling PA-API 5.0!
Status code: 429
Errors : {"__type":"com.amazon.paapi5#TooManyRequestsException","Errors":[{"Code":"TooManyRequests","Message":"The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API."}]}
```
How can I solve? thank you for your work

**Comment by samirsalman** [comment]
Hi,

the error is caused by amazon API. **You have spent your paapi(Amazon API) daily request,** you can find errors documentation at this page: _https://webservices.amazon.com/paapi5/documentation/troubleshooting/error-messages.html_

For your error the documentation says:
"If the requests at which Product Advertising API 5.0 is being hit is too high, it will result in this exception."

![image](https://user-images.githubusercontent.com/33979978/99298870-aec88580-284a-11eb-97e4-76b335350896.png)


You must wait tomorrow, look at your `PAUSE_MINUTE ` in the code. 
I hope you can solve the problem, if you not solve please write me.

Thank you for your issue and your star.

**Comment by AlejandroDieg0** [comment]
Thank you for the response, it happened just when started the bot, so I dont think I spent my paapi daily request. my pause_minute is 12 as by default, what value would help to get the bot workin'? thank you again

**Comment by samirsalman** [comment]
You can try to change row 49 in bot.py:

From `time.sleep(1)` to `time.sleep(3)`

Tell me if this solve your problem.

**Comment by AlejandroDieg0** [comment]
> You can try to change row 49 in bot.py:
> 
> From `time.sleep(1)` to `time.sleep(3)`
> 
> Tell me if this solve your problem.

not solved, on every request it says the same error. I'll wait until tomorrow to avoid thinking about problem to my Api key.
